spring:
  application:
    name: product
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/hicloud?characterEncoding=utf-8&useSSL=false
  jpa:
#      show-sql: true
      properties:
            hibernate:
              format_sql: true
              show_sql: true
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka